const g_blog_root = "/blog/";
const g_path_map = new Map();
g_path_map.set("/contact/", "/contact/index.html");
g_path_map.set(g_blog_root, g_blog_root+"index.html");
g_path_map.set(g_blog_root+"x86_vs_x64/", g_blog_root+"x86_vs_x64/index.html");
g_path_map.set(g_blog_root+"new_blog/", g_blog_root+"new_blog/index.html");
g_path_map.set(g_blog_root+"c++_the_mad_god/", g_blog_root+"c++_the_mad_god/index.html");

// this is all generated by chatgpt because i can't be asked to write js
async function loadPageHTML(url) {
	try {
		const response = await fetch(url);
		const htmlText = await response.text();

		const parser = new DOMParser();
		const doc = parser.parseFromString(htmlText, 'text/html');

		// replace entire head content
		document.head.innerHTML = doc.head.innerHTML;

		// Replace body content
		document.body.innerHTML = doc.body.innerHTML;
	} catch (err) {
		console.error('Failed to load HTML:', err);
	}
}

function handleRouting() {
	if(g_path_map.has(location.pathname)){
		loadPageHTML(g_path_map.get(location.pathname));
	}else if( location.pathname === "/"){
		loadPageHTML("index.html");
	}else{
		console.error("requested path: "+location.pathname+" does not exist");
	}
}

// On load
window.addEventListener('DOMContentLoaded', handleRouting);

// On navigation
window.addEventListener('popstate', handleRouting);

// Handle internal <a> clicks
document.addEventListener('click', (e) => {
	if (e.target.matches('a')) {
		const href = e.target.getAttribute('href');
		if (href.startsWith('/')) {
			e.preventDefault();
			history.pushState({}, '', href);
			handleRouting();
		}
	}
});
